# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'
permissions:
  contents: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout private repository
        uses: actions/checkout@v2
        with:
          repository: blog1703/m3u-updater
          token: ${{ secrets.tokeniptv }}  # Токен для доступа к приватному репозиторию

      - name: Install wget
        run: sudo apt-get install -y wget

      - name: Run update_iptv.sh
        run: bash update_iptv.sh

      - name: Checkout public repository
        uses: actions/checkout@v2
        with:
          repository: blog1703/public-repo
          path: public-repo
          token: ${{ secrets.PUBLIC_REPO_TOKEN }}  # Токен для доступа к публичному репозиторию

      - name: Copy M3U file to public repository
        run: |
          cp iptv.m3u public-repo/iptv.m3u
          cd public-repo
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add iptv.m3u
          git commit -m "Automated update of IPTV M3U file"
          git push

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PUBLIC_REPO_TOKEN }}
          publish_dir: ./tv
          keep_files: false
