name: Update M3U File

on:
  schedule:
    - cron: '0 3 * * *'  # Запускать каждый день в 3:00 UTC
  workflow_dispatch:  # Позволяет запускать вручную

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}  # Токен для приватных репозиториев

      - name: Update M3U file
        run: bash update_m3u.sh

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Automated M3U file update"
            git pull --rebase
            git push
          fi
