# This is a basic workflow to help you get started with Actions

name: Update M3U File

on:
  schedule:
    - cron: '0 3 * * *'  # Запускать каждый день в 3:00 UTC
  workflow_dispatch:  # Позволяет запускать вручную через интерфейс GitHub

jobs:
  update:
    runs-on: ubuntu-latest  # Используем последнюю версию Ubuntu

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Клонируем репозиторий

      - name: Update M3U file
        run: |
          # Запускаем скрипт для обновления файла
          bash update_m3u.sh

      - name: Commit and push changes
        run: |
          # Настраиваем Git
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          # Добавляем изменения и коммитим
          git add .
          git commit -m "Automated M3U file update"

          # Пушим изменения в репозиторий
          git push
